name: Warmenhoven Tasks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: gh repo sync $REPOSITORY -b master

